### ISSUE TITLE
We need an explanation

### ISSUE THREAD

**Issue by Gigiz** [propjockey/css-conways-game-of-life#1]
First of all, we salute you master of css :D
This is the global day of coderetreat, we were wondering if the game of life could be done in pure css, and here we are!

But we didn't understand your solution.

Can you provide a little bit of explanation in the readme about the techniques that you used? 

Thanks a lot and again good job!

@gabrielelana @fbrioccia as 👀

**Comment by JaneOri** [comment]
Thank you! So so sorry I didn't respond, I was hospitalized for 3 weeks like the day after you posted this and completely forgot it existed until I saw it yesterday.

Too late for your retreat but for your personal curiosity, the first version you were asking about at the time, works like this:

---

First, the dom is a series of `<i>` and `<b>` tags nested in each other until 60 elements deep

`<i><b><i><b><i><b>....<i><b>`

each one (i or b) is 1 frame of the entire field, with hundreds of --css-vars, each registered with `@property`, and not just one for every box on the 20x20 field, but several to calculate if it died, spawned, etc (Read about Game of Life rules if you want to know specifically what might be tracked)

The vars at every layer are computed with the exact same code; except that:
- `i` layers compute their values based on the inherited `b` value outputs
- `b` layers compute their values based on the inherited `i` value outputs

The code for both is otherwise identical.

Now then, `@property` is the most important feature here because it avoids hitting maximum `calc()` nesting depth by computing the calc into an integer, then only an integer is passed down to the next frame instead of a full "string" to re-compute.

The last important thing is that it `visibility: visible;` inside of a `visibility: hidden;` element is visible, not hidden.

So all 60 frames are nested as hidden, then I animate from the top of the stack down to the bottom and only show `visibility: visible;` on one frame at a time to give the illusion of change, the illusion of time, though everything exists here and now. Just like our "real life" physical reality simulation.

There are a few other tricks, and knowledge of how GoL frames are calculated that you can find on Wikipedia to infer what I must be doing in my `calc()`s, but that is the gist of the CSS trickery.

Happy to answer specifics if you have any questions!
