### ISSUE TITLE
doesn't work on firefox

### ISSUE THREAD

**Issue by eyaler** [propjockey/css-conways-game-of-life#2]
![image](https://github.com/propjockey/css-conways-game-of-life/assets/4436747/94cf2918-0008-402c-843c-32e7cf54c34b)

**Comment by JaneOri** [comment]
Oooh neat! Looks like a frame buffer overflow.

This is just a stress test / experiment / for fun and neither version is intended to work outside of browsers implementing the latest CSS features at speed

The version in your screenshot is particularly, egregiously, heavy in its implementation and gargantuan in its memory usage.

Nothing to do here, and very unlikely the Firefox could track down a problem from this source, sooo closing this, but thank you for checking it out and letting me know! :)

**Comment by eyaler** [comment]
@JaneOri thanks, your work is really inspiring and educational. i would be interested to understand what are the essential CSS features that make or break your approach.

**Comment by JaneOri** [comment]
For version 1 that you have pictured:

First, the dom is a series of `<i>` and `<b>` tags nested in each other until 60 elements deep

`<i><b><i><b><i><b>....<i><b>`

each one (i or b) is 1 frame of the entire field, with hundreds of --css-vars, each registered with `@property`, and not just one for every box on the 20x20 field, but several to calculate if it died, spawned, etc (Read about Game of Life rules if you want to know specifically what might be tracked)

The vars at every layer are computed with the exact same code; except that:
- `i` layers compute their values based on the inherited `b` value outputs
- `b` layers compute their values based on the inherited `i` value outputs

The code for both is otherwise identical.

Now then, `@property` is the most important feature here because it avoids hitting maximum `calc()` nesting depth by computing the calc into an integer, then only an integer is passed down to the next frame instead of a full "string" to re-compute. (firefox does not support `@property` yet)

The last important thing is that it `visibility: visible;` inside of a `visibility: hidden;` element is visible, not hidden.

So all 60 frames are nested as hidden, then I animate from the top of the stack down to the bottom and only show `visibility: visible;` on one frame at a time to give the illusion of change, the illusion of time, though everything exists here and now. Just like our "real life" physical reality simulation.

There are a few other tricks, and knowledge of how GoL frames are calculated that you can find on Wikipedia to infer what I must be doing in my `calc()`s, but that is the gist of the CSS trickery.

Happy to answer specifics if you have any questions!
